module.exports = [
    { room: 101, floor: 1, building: 'campus' },
    { room: 102, floor: 1, building: 'campus' },
    { room: 103, floor: 1, building: 'campus' },
    { room: 104, floor: 1, building: 'campus' },
    { room: 105, floor: 1, building: 'campus' },
    { room: 106, floor: 1, building: 'campus' },
    { room: 107, floor: 1, building: 'campus' },
    { room: 108, floor: 1, building: 'campus' },
    { room: 109, floor: 1, building: 'campus' },
    { room: 110, floor: 1, building: 'campus' },
    { room: 111, floor: 1, building: 'campus' },
    { room: 112, floor: 1, building: 'campus' },

    { room: 201, floor: 2, building: 'campus' },
    { room: 202, floor: 2, building: 'campus' },
    { room: 203, floor: 2, building: 'campus' },
    { room: 204, floor: 2, building: 'campus' },
    { room: 205, floor: 2, building: 'campus' },
    { room: 206, floor: 2, building: 'campus' },
    { room: 207, floor: 2, building: 'campus' },
    { room: 208, floor: 2, building: 'campus' },
    { room: 209, floor: 2, building: 'campus' },
    { room: 210, floor: 2, building: 'campus' },
    { room: 211, floor: 2, building: 'campus' },
    { room: 212, floor: 2, building: 'campus' },
    { room: 213, floor: 2, building: 'campus' },

    { room: 1, floor: 1, building: 'front' },
    { room: 2, floor: 1, building: 'front' },
    { room: 3, floor: 2, building: 'front' },
    { room: 4, floor: 2, building: 'front' },
    { room: 5, floor: 2, building: 'front' },
    { room: 6, floor: 2, building: 'front' }
];